export type Page =
  | "main"
  | "artist"
  | "metatheatre"
  | "shop"
  | "product"
  | "cart"
  | "checkout"
  | "success"
  | "cancelled"
  | "orderlookup"
  | "myorders"
  | "admin"
  | "adminrecovery"
  | "unsubscribe";
