import Map "mo:core/Map";
import Principal "mo:core/Principal";

module {
  // The stable identifier of a stored product image asset. Generated by the
  // canister at finishUpload time; immutable once committed. Used both as the
  // map key for the stored blob and as the path segment in the public asset
  // URL (/assets/products/<assetId>).
  public type AssetId = Text;

  // A committed product image asset stored in canister stable state. The bytes
  // are the full image blob; byteSize mirrors bytes.size() so the storage
  // accounting (getProductImageStorageStats) never has to re-read the blob.
  public type AssetRecord = {
    id : AssetId;
    contentType : Text;
    bytes : Blob;
    byteSize : Nat;
    uploadedAt : Int;
    productId : Nat;
  };

  // An in-progress chunked upload. Chunks are accumulated keyed by their index
  // until finishUpload validates the assembled size and commits the asset.
  // owner is bound from msg.caller at startUpload; only the owner may upload
  // further chunks or finish the session. lastActivityAt is bumped on every
  // chunk so the lazy sweep can expire abandoned sessions.
  public type UploadSession = {
    id : Text;
    owner : Principal;
    contentType : Text;
    totalSize : Nat;
    received : Map.Map<Nat, Blob>;
    createdAt : Int;
    lastActivityAt : Int;
  };

  // Upload / deletion error variants. Each maps to a distinct, actionable
  // failure the frontend can surface verbatim (never a generic "upload failed").
  public type UploadError = {
    // Caller is anonymous or not ADMIN/OWNER.
    #unauthorized;
    // The upload session or asset id does not exist.
    #notFound;
    // Content type is not one of image/jpeg, image/png, image/webp.
    #invalidContentType;
    // image/svg+xml is explicitly rejected as an XSS vector.
    #svgNotAllowed;
    // totalSize or assembled size exceeds the 2MB per-image limit.
    #tooLarge;
    // Assembled size at finishUpload does not match the declared totalSize.
    #sizeMismatch;
    // The declared content type contradicts the file's magic bytes.
    #magicByteMismatch;
    // The product already has the maximum (5) images.
    #tooManyImages;
    // A chunk index was received out of order or duplicated.
    #chunkOutOfOrder;
    // The upload session was abandoned and expired.
    #uploadExpired;
  };

  // Aggregate storage accounting for product images, surfaced in the admin
  // Canister tab so the operator can watch storage grow and the ongoing cycle
  // burn rate it implies.
  public type StorageStats = {
    totalBytes : Nat;
    count : Nat;
  };

  // --- IC HTTP interface types (asset serving) ---

  public type HttpRequest = {
    method : Text;
    url : Text;
    headers : [(Text, Text)];
    body : Blob;
  };

  public type HttpResponse = {
    status_code : Nat16;
    headers : [(Text, Text)];
    body : Blob;
    streaming_strategy : ?StreamingStrategy;
  };

  public type StreamingStrategy = {
    #Callback : {
      callback : StreamingCallback;
      token : StreamingCallbackToken;
    };
  };

  public type StreamingCallback = query (StreamingCallbackToken) -> async StreamingCallbackResponse;

  public type StreamingCallbackToken = {
    key : Text;
    content_encoding : Text;
    index : Nat;
    sha256 : ?Blob;
  };

  public type StreamingCallbackResponse = {
    body : Blob;
    token : ?StreamingCallbackToken;
  };
};
