/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminOrderDetail {
  'status' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'encryptedShipping' : [] | [Uint8Array],
  'cryptoStatus' : [] | [CryptoPaymentStatus],
  'createdAt' : bigint,
  'reference' : string,
  'amountOwed' : number,
  'updatedAt' : bigint,
  'currency' : string,
  'hasShippingDetails' : boolean,
  'subaccountHex' : string,
  'items' : Array<OrderItem>,
  'sweepNote' : [] | [string],
  'customerEmail' : string,
  'depositAccountText' : string,
}
export interface AdminOrderView {
  'status' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'cryptoStatus' : [] | [CryptoPaymentStatus],
  'createdAt' : bigint,
  'itemCount' : bigint,
  'reference' : string,
  'amountOwed' : number,
  'currency' : string,
  'subaccountHex' : string,
  'sweepNote' : [] | [string],
  'customerEmail' : string,
  'depositAccountText' : string,
}
export interface Category {
  'id' : CategoryId,
  'updated_at' : bigint,
  'active' : boolean,
  'sortOrder' : bigint,
  'name' : string,
  'slug' : string,
  'description' : [] | [string],
  'created_at' : bigint,
  'showWhenEmpty' : boolean,
}
export type CategoryError = { 'emptyName' : null } |
  { 'targetCategoryNotFound' : string } |
  { 'notFound' : CategoryId } |
  { 'productsReferenced' : { 'count' : bigint, 'slug' : string } } |
  { 'slugCollision' : string };
export type CategoryId = bigint;
export interface CategoryWithCount {
  'productCount' : bigint,
  'category' : Category,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface CheckoutSession { 'url' : [] | [string], 'reference' : string }
export type ConsentError = { 'alreadyUnsubscribed' : null } |
  { 'notConfigured' : string } |
  { 'invalidToken' : null } |
  { 'rateLimited' : null } |
  { 'outcallFailed' : string } |
  { 'unauthorized' : null } |
  { 'invalidResponse' : string };
export interface ConsentListExport { 'csv' : string }
export interface CreateOrderInput {
  'payment_method' : PaymentMethod,
  'has_shipping_details' : boolean,
  'items' : Array<CreateOrderItem>,
  'customer_email' : string,
  'encrypted_shipping' : [] | [Uint8Array],
  'marketing_consent' : boolean,
}
export interface CreateOrderItem {
  'product_id' : ProductId,
  'variant_id' : string,
  'quantity' : bigint,
}
export interface CreateOrderResult {
  'order' : Order,
  'cancellationToken' : [] | [string],
}
export interface CryptoConfigView {
  'icp' : LedgerConfig,
  'ckUSDC' : LedgerConfig,
  'treasurySubaccount' : [] | [Uint8Array],
  'minimumOrder' : number,
  'ckUSDCEnabled' : boolean,
  'treasuryPrincipal' : Principal,
}
export type CryptoPaymentError = { 'alreadyPaid' : null } |
  { 'overpayment' : { 'expected' : bigint, 'received' : bigint } } |
  { 'expired' : null } |
  { 'underpayment' : { 'expected' : bigint, 'received' : bigint } } |
  { 'sweepFailed' : string } |
  { 'notFound' : null } |
  { 'ledgerError' : string } |
  { 'notCryptoOrder' : null } |
  { 'unauthorized' : null } |
  { 'invalidConfig' : string } |
  { 'belowMinimumOrder' : number };
export type CryptoPaymentStatus = {
    'overpayment' : { 'expected' : bigint, 'received' : bigint }
  } |
  { 'expired' : null } |
  { 'underpayment' : { 'expected' : bigint, 'received' : bigint } } |
  { 'paid' : { 'blockIndex' : bigint } } |
  { 'awaiting_payment' : null };
export interface DepositAccount {
  'owner' : Principal,
  'subaccount' : Uint8Array,
  'textAddress' : string,
}
export interface DepositInfo {
  'decimals' : number,
  'token' : Token,
  'expiresAt' : bigint,
  'qrPayload' : string,
  'subaccount' : Uint8Array,
  'reference' : string,
  'address' : Principal,
  'amountDue' : bigint,
}
export type Discipline = { 'music' : null } |
  { 'other' : null } |
  { 'video' : null } |
  { 'visualArt' : null } |
  { 'writing' : null };
export type EmailError = { 'notConfigured' : string } |
  { 'notShippable' : null } |
  { 'notFound' : null } |
  { 'outcallFailed' : string } |
  { 'unauthorized' : null } |
  { 'invalidResponse' : string };
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequest {
  'url' : string,
  'method' : string,
  'body' : Uint8Array,
  'headers' : Array<[string, string]>,
}
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface HttpResponse {
  'body' : Uint8Array,
  'headers' : Array<[string, string]>,
  'streaming_strategy' : [] | [StreamingStrategy],
  'status_code' : number,
}
export interface LatePayment {
  'token' : Token,
  'reference' : string,
  'receivedAmount' : bigint,
  'receivedAt' : bigint,
  'reviewed' : boolean,
  'expectedAmount' : bigint,
}
export interface LedgerConfig {
  'fee' : bigint,
  'decimals' : number,
  'canisterId' : Principal,
}
export interface Order {
  'id' : bigint,
  'tax' : number,
  'updated_at' : bigint,
  'total' : number,
  'sweep_note' : [] | [string],
  'shipping' : number,
  'reference' : string,
  'created_at' : bigint,
  'payment_status' : PaymentStatus,
  'payment_method' : PaymentMethod,
  'tracking_number' : [] | [string],
  'currency' : string,
  'marketing_consent_at' : [] | [bigint],
  'shipping_status' : ShippingStatus,
  'has_shipping_details' : boolean,
  'items' : Array<OrderItem>,
  'customer_email' : string,
  'encrypted_shipping' : [] | [Uint8Array],
  'customer_principal' : [] | [Principal],
  'shipped_at' : [] | [bigint],
  'marketing_consent' : boolean,
  'payment_reference' : [] | [string],
  'subtotal' : number,
}
export type OrderError = { 'outOfStock' : [ProductId, string] } |
  { 'unknownVariant' : [ProductId, string] } |
  { 'unknownProduct' : ProductId } |
  { 'ckUSDCDisabled' : null } |
  { 'emptyOrder' : null } |
  { 'rateLimited' : null } |
  { 'belowMinimumOrder' : number } |
  { 'productInactive' : ProductId } |
  { 'paymentFailed' : string } |
  { 'invalidQuantity' : null } |
  { 'tooManyPendingOrders' : null };
export interface OrderItem {
  'product_id' : ProductId,
  'unit_amount' : number,
  'name' : string,
  'variant_id' : string,
  'quantity' : bigint,
}
export interface OrderRecoveryView {
  'status' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'expiresAt' : [] | [bigint],
  'reference' : string,
  'depositAccount' : [] | [DepositAccount],
  'amountOwed' : number,
  'liveBalance' : bigint,
}
export type PaymentError = { 'invalidOrder' : null } |
  { 'paymentFailed' : string };
export type PaymentMethod = { 'crypto_icp' : null } |
  { 'card_stripe' : null } |
  { 'crypto_ckusdc' : null } |
  { 'manual' : null };
export interface PaymentServiceConfigView {
  'url' : string,
  'tokenSet' : boolean,
}
export type PaymentServiceError = { 'alreadyPaid' : null } |
  { 'notConfigured' : string } |
  { 'notFound' : null } |
  { 'rateLimited' : null } |
  { 'outcallFailed' : string } |
  { 'unauthorized' : null } |
  { 'invalidResponse' : string };
export type PaymentStatus = { 'cancelled' : null } |
  { 'expired' : null } |
  { 'pending' : null } |
  { 'paid' : null };
export interface Product {
  'id' : ProductId,
  'updated_at' : bigint,
  'active' : boolean,
  'inventory' : bigint,
  'name' : string,
  'slug' : string,
  'description' : string,
  'variants' : Array<ProductVariant>,
  'created_at' : bigint,
  'currency' : string,
  'admin_only' : boolean,
  'category' : string,
  'price' : number,
  'images' : Array<string>,
}
export type ProductId = bigint;
export interface ProductVariant {
  'id' : string,
  'inventory' : bigint,
  'name' : string,
  'size' : string,
  'price' : number,
}
export interface PublicOrderView {
  'id' : bigint,
  'tax' : number,
  'updated_at' : bigint,
  'total' : number,
  'sweep_note' : [] | [string],
  'shipping' : number,
  'reference' : string,
  'created_at' : bigint,
  'payment_status' : PaymentStatus,
  'payment_method' : PaymentMethod,
  'tracking_number' : [] | [string],
  'currency' : string,
  'marketing_consent_at' : [] | [bigint],
  'shipping_status' : ShippingStatus,
  'has_shipping_details' : boolean,
  'items' : Array<OrderItem>,
  'encrypted_shipping' : [] | [Uint8Array],
  'customer_principal' : [] | [Principal],
  'shipped_at' : [] | [bigint],
  'marketing_consent' : boolean,
  'payment_reference' : [] | [string],
  'subtotal' : number,
}
export interface RecheckResult {
  'status' : CryptoPaymentStatus,
  'balance' : bigint,
  'reference' : string,
  'error' : [] | [string],
}
export type RecoveryError = { 'sweepFailed' : string } |
  { 'notFound' : null } |
  { 'ledgerError' : string } |
  { 'notCryptoOrder' : null } |
  { 'unauthorized' : null } |
  { 'invalidConfig' : string };
export type Result = { 'ok' : null } |
  { 'err' : UploadError };
export type Result_1 = { 'ok' : null } |
  { 'err' : CryptoPaymentError };
export type Result_10 = { 'ok' : null } |
  { 'err' : EmailError };
export type Result_11 = { 'ok' : null } |
  { 'err' : CategoryError };
export type Result_12 = { 'ok' : bigint } |
  { 'err' : CategoryError };
export type Result_13 = { 'ok' : Array<SubmissionRecord> } |
  { 'err' : SubmissionError };
export type Result_14 = { 'ok' : null } |
  { 'err' : PaymentError };
export type Result_15 = { 'ok' : SubaccountBalanceResult } |
  { 'err' : SweepError };
export type Result_16 = { 'ok' : ResumeInfo } |
  { 'err' : RecoveryError };
export type Result_17 = { 'ok' : bigint } |
  { 'err' : RecoveryError };
export type Result_18 = { 'ok' : CryptoPaymentStatus } |
  { 'err' : CryptoPaymentError };
export type Result_19 = { 'ok' : DepositInfo } |
  { 'err' : CryptoPaymentError };
export type Result_2 = { 'ok' : null } |
  { 'err' : PaymentServiceError };
export type Result_20 = { 'ok' : ConsentListExport } |
  { 'err' : ConsentError };
export type Result_21 = { 'ok' : RecheckResult } |
  { 'err' : RecoveryError };
export type Result_22 = { 'ok' : CreateOrderResult } |
  { 'err' : OrderError };
export type Result_23 = { 'ok' : CheckoutSession } |
  { 'err' : PaymentError };
export type Result_24 = { 'ok' : CheckoutSession } |
  { 'err' : PaymentServiceError };
export type Result_25 = { 'ok' : PaymentStatus } |
  { 'err' : PaymentServiceError };
export type Result_3 = { 'ok' : Category } |
  { 'err' : CategoryError };
export type Result_4 = { 'ok' : null } |
  { 'err' : ConsentError };
export type Result_5 = { 'ok' : SweepSubaccountResult } |
  { 'err' : SweepError };
export type Result_6 = { 'ok' : SweepResult } |
  { 'err' : RecoveryError };
export type Result_7 = { 'ok' : bigint } |
  { 'err' : CryptoPaymentError };
export type Result_8 = { 'ok' : null } |
  { 'err' : SubmissionError };
export type Result_9 = { 'ok' : string } |
  { 'err' : UploadError };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface ResumeInfo {
  'status' : CryptoPaymentStatus,
  'expiresAt' : bigint,
  'reference' : string,
  'deposit' : [] | [DepositInfo],
  'remainingNs' : bigint,
}
export type Role = { 'admin' : null } |
  { 'owner' : null } |
  { 'staff' : null };
export type ShippingStatus = { 'shipped' : null } |
  { 'pending' : null };
export interface StorageStats { 'count' : bigint, 'totalBytes' : bigint }
export type StreamingCallback = ActorMethod<
  [StreamingCallbackToken],
  StreamingCallbackResponse
>;
export interface StreamingCallbackResponse {
  'token' : [] | [StreamingCallbackToken],
  'body' : Uint8Array,
}
export interface StreamingCallbackToken {
  'key' : string,
  'sha256' : [] | [Uint8Array],
  'index' : bigint,
  'content_encoding' : string,
}
export type StreamingStrategy = {
    'Callback' : {
      'token' : StreamingCallbackToken,
      'callback' : [Principal, string],
    }
  };
export interface SubaccountBalanceResult {
  'balance' : bigint,
  'subaccountHex' : string,
  'subaccountIndex' : bigint,
}
export type SubmissionError = { 'invalidInput' : string } |
  { 'notConfigured' : string } |
  { 'honeypot' : null } |
  { 'rateLimited' : null } |
  { 'outcallFailed' : string } |
  { 'invalidResponse' : string };
export interface SubmissionInput {
  'discipline' : Discipline,
  'link' : string,
  'name' : string,
  'email' : string,
  'message' : [] | [string],
  'honeypot' : string,
  'marketingConsentAt' : [] | [bigint],
  'marketingConsent' : boolean,
}
export interface SubmissionRecord {
  'id' : string,
  'discipline' : Discipline,
  'link' : string,
  'name' : string,
  'submittedAt' : bigint,
  'email' : string,
  'message' : [] | [string],
  'marketingConsentAt' : [] | [bigint],
  'marketingConsent' : boolean,
}
export type SweepError = { 'sweepFailed' : string } |
  { 'ledgerError' : string } |
  { 'unauthorized' : null } |
  { 'invalidConfig' : string };
export interface SweepResult {
  'reference' : [] | [string],
  'error' : [] | [string],
  'blockIndex' : [] | [bigint],
}
export interface SweepSubaccountResult {
  'error' : [] | [string],
  'blockIndex' : [] | [bigint],
  'subaccountHex' : string,
  'subaccountIndex' : bigint,
}
export type Token = { 'ICP' : null } |
  { 'ckUSDC' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type UploadError = { 'tooManyImages' : null } |
  { 'tooLarge' : null } |
  { 'magicByteMismatch' : null } |
  { 'sizeMismatch' : null } |
  { 'invalidContentType' : null } |
  { 'notFound' : null } |
  { 'uploadExpired' : null } |
  { 'svgNotAllowed' : null } |
  { 'chunkOutOfOrder' : null } |
  { 'unauthorized' : null };
export interface UserRecord { 'grantedAt' : bigint, 'role' : Role }
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  'addAdmin' : ActorMethod<[Principal], boolean>,
  'adminCount' : ActorMethod<[], bigint>,
  'adminGetOrderDetail' : ActorMethod<[string], [] | [AdminOrderDetail]>,
  'adminListOrders' : ActorMethod<[string], Array<AdminOrderView>>,
  'bootstrapOwner' : ActorMethod<[Principal], boolean>,
  'cancelCardOrder' : ActorMethod<[string], Result_2>,
  'cancelGuestOrder' : ActorMethod<[string, string], Result_2>,
  'checkCryptoPayment' : ActorMethod<[string], Result_18>,
  'claimInitialAdmin' : ActorMethod<[], boolean>,
  'confirmCardPayment' : ActorMethod<[string], Result_25>,
  'consentServiceTransform' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'createCardCheckoutSession' : ActorMethod<
    [string, string, string],
    Result_24
  >,
  'createCategory' : ActorMethod<[string, [] | [string]], Result_3>,
  'createCheckoutSession' : ActorMethod<[Order], Result_23>,
  'createOrder' : ActorMethod<[CreateOrderInput], Result_22>,
  'createProduct' : ActorMethod<[Product], boolean>,
  'deleteCategory' : ActorMethod<[CategoryId], Result_11>,
  'deleteProductImage' : ActorMethod<[string], Result>,
  'emailTransform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'execute' : ActorMethod<[string], Result__1>,
  'finishUpload' : ActorMethod<[string, bigint], Result_9>,
  'forceRecheckPayment' : ActorMethod<[string], Result_21>,
  'forceSweepOrder' : ActorMethod<[string], Result_6>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCanisterId' : ActorMethod<[], Principal>,
  'getConsentListCsv' : ActorMethod<[], Result_20>,
  'getCryptoConfig' : ActorMethod<[], CryptoConfigView>,
  'getCryptoDepositInfo' : ActorMethod<[string], Result_19>,
  'getCryptoPaymentStatus' : ActorMethod<[string], Result_18>,
  'getCycleBalance' : ActorMethod<[], bigint>,
  'getDashboardData' : ActorMethod<[], string>,
  'getDefaultSubaccountBalance' : ActorMethod<[], Result_17>,
  'getEncryptionRecipients' : ActorMethod<[], Array<Principal>>,
  'getIbePublicKey' : ActorMethod<[], Uint8Array>,
  'getMinimumOrder' : ActorMethod<[], number>,
  'getMyEncryptedIbeKey' : ActorMethod<[Uint8Array], Uint8Array>,
  'getMyOrders' : ActorMethod<[], Array<PublicOrderView>>,
  'getMyRole' : ActorMethod<[], [] | [Role]>,
  'getNAKPrice' : ActorMethod<[], string>,
  'getOrderStatus' : ActorMethod<[string], [] | [PublicOrderView]>,
  'getPaymentServiceConfig' : ActorMethod<[], PaymentServiceConfigView>,
  'getPaymentStatus' : ActorMethod<[string], PaymentStatus>,
  'getProduct' : ActorMethod<[string], [] | [Product]>,
  'getProductImageStorageStats' : ActorMethod<[], StorageStats>,
  'getResumeInfo' : ActorMethod<[string], Result_16>,
  'getSubaccountBalance' : ActorMethod<[bigint], Result_15>,
  'getTokenImage' : ActorMethod<[string, string], string>,
  'getTokenProfile' : ActorMethod<[string, string], string>,
  'getTreasuryTokens' : ActorMethod<[], string>,
  'grantRole' : ActorMethod<[Principal, Role], boolean>,
  'handlePaymentConfirmation' : ActorMethod<[string], Result_14>,
  'http_request' : ActorMethod<[HttpRequest], HttpResponse>,
  'http_request_streaming_callback' : ActorMethod<
    [StreamingCallbackToken],
    StreamingCallbackResponse
  >,
  'http_request_update' : ActorMethod<[HttpRequest], HttpResponse>,
  'isAdmin' : ActorMethod<[], boolean>,
  'listAdmins' : ActorMethod<[], Array<Principal>>,
  'listCategories' : ActorMethod<[], Array<CategoryWithCount>>,
  'listLatePayments' : ActorMethod<[], Array<LatePayment>>,
  'listOrdersForRecovery' : ActorMethod<[], Array<OrderRecoveryView>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'listSubmissions' : ActorMethod<[], Result_13>,
  'listUsers' : ActorMethod<[], Array<[Principal, UserRecord]>>,
  'markLatePaymentReviewed' : ActorMethod<[string], boolean>,
  'markOrderShipped' : ActorMethod<[string, [] | [string]], Result_10>,
  'paymentServiceTransform' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'reassignProducts' : ActorMethod<[string, string], Result_12>,
  'releaseExpiredOrders' : ActorMethod<[], bigint>,
  'removeAdmin' : ActorMethod<[Principal], boolean>,
  'reorderCategories' : ActorMethod<[Array<CategoryId>], Result_11>,
  'resendConfirmationEmail' : ActorMethod<[string], Result_10>,
  'resetAdminForMigration' : ActorMethod<[], boolean>,
  'revokeRole' : ActorMethod<[Principal], boolean>,
  'schema' : ActorMethod<[], string>,
  'startUpload' : ActorMethod<[string, bigint], Result_9>,
  'startVerificationTimer' : ActorMethod<[], boolean>,
  'stopVerificationTimer' : ActorMethod<[], boolean>,
  'submissionServiceTransform' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'submitSubmission' : ActorMethod<[SubmissionInput], Result_8>,
  'sweepCryptoToTreasury' : ActorMethod<[string], Result_7>,
  'sweepDefaultSubaccount' : ActorMethod<[], Result_6>,
  'sweepExpiredUploads' : ActorMethod<[], undefined>,
  'sweepSubaccount' : ActorMethod<[bigint], Result_5>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unsubscribe' : ActorMethod<[string], Result_4>,
  'updateCategory' : ActorMethod<
    [CategoryId, string, [] | [string], bigint, boolean, boolean],
    Result_3
  >,
  'updateLedgerConfig' : ActorMethod<
    [Token, Principal, number, bigint],
    Result_1
  >,
  'updateMinimumOrder' : ActorMethod<[number], Result_1>,
  'updatePaymentServiceToken' : ActorMethod<[string], Result_2>,
  'updatePaymentServiceUrl' : ActorMethod<[string], Result_2>,
  'updateProduct' : ActorMethod<[Product], boolean>,
  'updateTreasury' : ActorMethod<[Principal, [] | [Uint8Array]], Result_1>,
  'uploadChunk' : ActorMethod<[string, bigint, Uint8Array], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];