/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PaymentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'expired' : IDL.Null,
  'pending' : IDL.Null,
  'paid' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'crypto_icp' : IDL.Null,
  'card_stripe' : IDL.Null,
  'crypto_ckusdc' : IDL.Null,
  'manual' : IDL.Null,
});
export const CryptoPaymentStatus = IDL.Variant({
  'overpayment' : IDL.Record({ 'expected' : IDL.Nat, 'received' : IDL.Nat }),
  'expired' : IDL.Null,
  'underpayment' : IDL.Record({ 'expected' : IDL.Nat, 'received' : IDL.Nat }),
  'paid' : IDL.Record({ 'blockIndex' : IDL.Nat }),
  'awaiting_payment' : IDL.Null,
});
export const ProductId = IDL.Nat;
export const OrderItem = IDL.Record({
  'product_id' : ProductId,
  'unit_amount' : IDL.Nat,
  'name' : IDL.Text,
  'variant_id' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const AdminOrderDetail = IDL.Record({
  'status' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'encryptedShipping' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'cryptoStatus' : IDL.Opt(CryptoPaymentStatus),
  'createdAt' : IDL.Int,
  'reference' : IDL.Text,
  'amountOwed' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'currency' : IDL.Text,
  'hasShippingDetails' : IDL.Bool,
  'subaccountHex' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'sweepNote' : IDL.Opt(IDL.Text),
  'customerEmail' : IDL.Text,
  'depositAccountText' : IDL.Text,
});
export const AdminOrderView = IDL.Record({
  'status' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'cryptoStatus' : IDL.Opt(CryptoPaymentStatus),
  'createdAt' : IDL.Int,
  'itemCount' : IDL.Nat,
  'reference' : IDL.Text,
  'amountOwed' : IDL.Nat,
  'currency' : IDL.Text,
  'subaccountHex' : IDL.Text,
  'sweepNote' : IDL.Opt(IDL.Text),
  'customerEmail' : IDL.Text,
  'depositAccountText' : IDL.Text,
});
export const PaymentServiceError = IDL.Variant({
  'alreadyPaid' : IDL.Null,
  'notConfigured' : IDL.Text,
  'notFound' : IDL.Null,
  'rateLimited' : IDL.Null,
  'outcallFailed' : IDL.Text,
  'unauthorized' : IDL.Null,
  'invalidResponse' : IDL.Text,
});
export const Result_2 = IDL.Variant({
  'ok' : IDL.Null,
  'err' : PaymentServiceError,
});
export const CryptoPaymentError = IDL.Variant({
  'alreadyPaid' : IDL.Null,
  'overpayment' : IDL.Record({ 'expected' : IDL.Nat, 'received' : IDL.Nat }),
  'expired' : IDL.Null,
  'underpayment' : IDL.Record({ 'expected' : IDL.Nat, 'received' : IDL.Nat }),
  'sweepFailed' : IDL.Text,
  'notFound' : IDL.Null,
  'ledgerError' : IDL.Text,
  'notCryptoOrder' : IDL.Null,
  'unauthorized' : IDL.Null,
  'invalidConfig' : IDL.Text,
  'belowMinimumOrder' : IDL.Nat,
});
export const Result_19 = IDL.Variant({
  'ok' : CryptoPaymentStatus,
  'err' : CryptoPaymentError,
});
export const Result_26 = IDL.Variant({
  'ok' : PaymentStatus,
  'err' : PaymentServiceError,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpRequestResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpRequestResult,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const CheckoutSession = IDL.Record({
  'url' : IDL.Opt(IDL.Text),
  'reference' : IDL.Text,
});
export const Result_25 = IDL.Variant({
  'ok' : CheckoutSession,
  'err' : PaymentServiceError,
});
export const CategoryId = IDL.Nat;
export const Category = IDL.Record({
  'id' : CategoryId,
  'updated_at' : IDL.Int,
  'active' : IDL.Bool,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'created_at' : IDL.Int,
  'showWhenEmpty' : IDL.Bool,
});
export const CategoryError = IDL.Variant({
  'emptyName' : IDL.Null,
  'targetCategoryNotFound' : IDL.Text,
  'notFound' : CategoryId,
  'productsReferenced' : IDL.Record({ 'count' : IDL.Nat, 'slug' : IDL.Text }),
  'slugCollision' : IDL.Text,
});
export const Result_4 = IDL.Variant({ 'ok' : Category, 'err' : CategoryError });
export const ShippingStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'pending' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'tax' : IDL.Nat,
  'updated_at' : IDL.Int,
  'total' : IDL.Nat,
  'sweep_note' : IDL.Opt(IDL.Text),
  'shipping' : IDL.Nat,
  'reference' : IDL.Text,
  'created_at' : IDL.Int,
  'payment_status' : PaymentStatus,
  'payment_method' : PaymentMethod,
  'tracking_number' : IDL.Opt(IDL.Text),
  'currency' : IDL.Text,
  'marketing_consent_at' : IDL.Opt(IDL.Int),
  'shipping_status' : ShippingStatus,
  'has_shipping_details' : IDL.Bool,
  'items' : IDL.Vec(OrderItem),
  'customer_email' : IDL.Text,
  'encrypted_shipping' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'customer_principal' : IDL.Opt(IDL.Principal),
  'shipped_at' : IDL.Opt(IDL.Int),
  'marketing_consent' : IDL.Bool,
  'payment_reference' : IDL.Opt(IDL.Text),
  'subtotal' : IDL.Nat,
});
export const PaymentError = IDL.Variant({
  'invalidOrder' : IDL.Null,
  'paymentFailed' : IDL.Text,
});
export const Result_24 = IDL.Variant({
  'ok' : CheckoutSession,
  'err' : PaymentError,
});
export const CreateOrderItem = IDL.Record({
  'product_id' : ProductId,
  'variant_id' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const CreateOrderInput = IDL.Record({
  'session_id' : IDL.Opt(IDL.Text),
  'payment_method' : PaymentMethod,
  'has_shipping_details' : IDL.Bool,
  'items' : IDL.Vec(CreateOrderItem),
  'customer_email' : IDL.Text,
  'encrypted_shipping' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'marketing_consent' : IDL.Bool,
});
export const CreateOrderResult = IDL.Record({
  'order' : Order,
  'cancellationToken' : IDL.Opt(IDL.Text),
  'sessionId' : IDL.Opt(IDL.Text),
});
export const OrderError = IDL.Variant({
  'outOfStock' : IDL.Tuple(ProductId, IDL.Text),
  'invalidPrice' : IDL.Text,
  'unknownVariant' : IDL.Tuple(ProductId, IDL.Text),
  'unknownProduct' : ProductId,
  'ckUSDCDisabled' : IDL.Null,
  'emptyOrder' : IDL.Null,
  'rateLimited' : IDL.Null,
  'belowMinimumOrder' : IDL.Nat,
  'productInactive' : ProductId,
  'paymentFailed' : IDL.Text,
  'invalidQuantity' : IDL.Null,
  'tooManyPendingOrders' : IDL.Null,
});
export const Result_23 = IDL.Variant({
  'ok' : CreateOrderResult,
  'err' : OrderError,
});
export const ProductVariant = IDL.Record({
  'id' : IDL.Text,
  'inventory' : IDL.Nat,
  'name' : IDL.Text,
  'size' : IDL.Text,
  'price' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'updated_at' : IDL.Int,
  'active' : IDL.Bool,
  'inventory' : IDL.Nat,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'variants' : IDL.Vec(ProductVariant),
  'created_at' : IDL.Int,
  'currency' : IDL.Text,
  'admin_only' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});
export const Result_12 = IDL.Variant({
  'ok' : IDL.Null,
  'err' : CategoryError,
});
export const UploadError = IDL.Variant({
  'tooManyImages' : IDL.Null,
  'tooLarge' : IDL.Null,
  'magicByteMismatch' : IDL.Null,
  'sizeMismatch' : IDL.Null,
  'invalidContentType' : IDL.Null,
  'notFound' : IDL.Null,
  'uploadExpired' : IDL.Null,
  'svgNotAllowed' : IDL.Null,
  'chunkOutOfOrder' : IDL.Null,
  'unauthorized' : IDL.Null,
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : UploadError });
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const Result_10 = IDL.Variant({ 'ok' : IDL.Text, 'err' : UploadError });
export const RecheckResult = IDL.Record({
  'status' : CryptoPaymentStatus,
  'balance' : IDL.Nat,
  'reference' : IDL.Text,
  'error' : IDL.Opt(IDL.Text),
});
export const RecoveryError = IDL.Variant({
  'sweepFailed' : IDL.Text,
  'notFound' : IDL.Null,
  'ledgerError' : IDL.Text,
  'notCryptoOrder' : IDL.Null,
  'unauthorized' : IDL.Null,
  'invalidConfig' : IDL.Text,
});
export const Result_22 = IDL.Variant({
  'ok' : RecheckResult,
  'err' : RecoveryError,
});
export const SweepResult = IDL.Record({
  'reference' : IDL.Opt(IDL.Text),
  'error' : IDL.Opt(IDL.Text),
  'blockIndex' : IDL.Opt(IDL.Nat),
});
export const Result_7 = IDL.Variant({
  'ok' : SweepResult,
  'err' : RecoveryError,
});
export const ConsentListExport = IDL.Record({ 'csv' : IDL.Text });
export const ConsentError = IDL.Variant({
  'alreadyUnsubscribed' : IDL.Null,
  'notConfigured' : IDL.Text,
  'invalidToken' : IDL.Null,
  'rateLimited' : IDL.Null,
  'outcallFailed' : IDL.Text,
  'unauthorized' : IDL.Null,
  'invalidResponse' : IDL.Text,
});
export const Result_21 = IDL.Variant({
  'ok' : ConsentListExport,
  'err' : ConsentError,
});
export const LedgerConfig = IDL.Record({
  'fee' : IDL.Nat,
  'decimals' : IDL.Nat8,
  'canisterId' : IDL.Principal,
});
export const CryptoConfigView = IDL.Record({
  'icp' : LedgerConfig,
  'ckUSDC' : LedgerConfig,
  'treasurySubaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'minimumOrder' : IDL.Nat,
  'ckUSDCEnabled' : IDL.Bool,
  'treasuryPrincipal' : IDL.Principal,
});
export const Token = IDL.Variant({ 'ICP' : IDL.Null, 'ckUSDC' : IDL.Null });
export const DepositInfo = IDL.Record({
  'decimals' : IDL.Nat8,
  'token' : Token,
  'expiresAt' : IDL.Int,
  'qrPayload' : IDL.Text,
  'subaccount' : IDL.Vec(IDL.Nat8),
  'reference' : IDL.Text,
  'address' : IDL.Principal,
  'amountDue' : IDL.Nat,
});
export const Result_20 = IDL.Variant({
  'ok' : DepositInfo,
  'err' : CryptoPaymentError,
});
export const Result_18 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : RecoveryError });
export const PublicOrderView = IDL.Record({
  'id' : IDL.Nat,
  'tax' : IDL.Float64,
  'updated_at' : IDL.Int,
  'total' : IDL.Float64,
  'sweep_note' : IDL.Opt(IDL.Text),
  'shipping' : IDL.Float64,
  'reference' : IDL.Text,
  'created_at' : IDL.Int,
  'payment_status' : PaymentStatus,
  'payment_method' : PaymentMethod,
  'tracking_number' : IDL.Opt(IDL.Text),
  'currency' : IDL.Text,
  'marketing_consent_at' : IDL.Opt(IDL.Int),
  'shipping_status' : ShippingStatus,
  'has_shipping_details' : IDL.Bool,
  'items' : IDL.Vec(OrderItem),
  'encrypted_shipping' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'customer_principal' : IDL.Opt(IDL.Principal),
  'shipped_at' : IDL.Opt(IDL.Int),
  'marketing_consent' : IDL.Bool,
  'payment_reference' : IDL.Opt(IDL.Text),
  'subtotal' : IDL.Float64,
});
export const Role = IDL.Variant({
  'admin' : IDL.Null,
  'owner' : IDL.Null,
  'staff' : IDL.Null,
});
export const PaymentServiceConfigView = IDL.Record({
  'url' : IDL.Text,
  'tokenSet' : IDL.Bool,
});
export const StorageStats = IDL.Record({
  'count' : IDL.Nat,
  'totalBytes' : IDL.Nat,
});
export const ResumeInfo = IDL.Record({
  'status' : CryptoPaymentStatus,
  'expiresAt' : IDL.Int,
  'reference' : IDL.Text,
  'deposit' : IDL.Opt(DepositInfo),
  'remainingNs' : IDL.Int,
});
export const Result_17 = IDL.Variant({
  'ok' : ResumeInfo,
  'err' : RecoveryError,
});
export const SubaccountBalanceResult = IDL.Record({
  'balance' : IDL.Nat,
  'subaccountHex' : IDL.Text,
  'subaccountIndex' : IDL.Nat,
});
export const SweepError = IDL.Variant({
  'sweepFailed' : IDL.Text,
  'ledgerError' : IDL.Text,
  'unauthorized' : IDL.Null,
  'invalidConfig' : IDL.Text,
});
export const Result_16 = IDL.Variant({
  'ok' : SubaccountBalanceResult,
  'err' : SweepError,
});
export const Result_15 = IDL.Variant({ 'ok' : IDL.Null, 'err' : PaymentError });
export const HttpRequest = IDL.Record({
  'url' : IDL.Text,
  'method' : IDL.Text,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
});
export const StreamingCallbackToken = IDL.Record({
  'key' : IDL.Text,
  'sha256' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'index' : IDL.Nat,
  'content_encoding' : IDL.Text,
});
export const StreamingCallbackResponse = IDL.Record({
  'token' : IDL.Opt(StreamingCallbackToken),
  'body' : IDL.Vec(IDL.Nat8),
});
export const StreamingCallback = IDL.Func(
    [StreamingCallbackToken],
    [StreamingCallbackResponse],
    ['query'],
  );
export const StreamingStrategy = IDL.Variant({
  'Callback' : IDL.Record({
    'token' : StreamingCallbackToken,
    'callback' : StreamingCallback,
  }),
});
export const HttpResponse = IDL.Record({
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'streaming_strategy' : IDL.Opt(StreamingStrategy),
  'status_code' : IDL.Nat16,
});
export const CategoryWithCount = IDL.Record({
  'productCount' : IDL.Nat,
  'category' : Category,
});
export const LatePayment = IDL.Record({
  'token' : Token,
  'reference' : IDL.Text,
  'receivedAmount' : IDL.Nat,
  'receivedAt' : IDL.Int,
  'reviewed' : IDL.Bool,
  'expectedAmount' : IDL.Nat,
});
export const DepositAccount = IDL.Record({
  'owner' : IDL.Principal,
  'subaccount' : IDL.Vec(IDL.Nat8),
  'textAddress' : IDL.Text,
});
export const OrderRecoveryView = IDL.Record({
  'status' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'expiresAt' : IDL.Opt(IDL.Int),
  'reference' : IDL.Text,
  'depositAccount' : IDL.Opt(DepositAccount),
  'amountOwed' : IDL.Nat,
  'liveBalance' : IDL.Nat,
});
export const Discipline = IDL.Variant({
  'music' : IDL.Null,
  'other' : IDL.Null,
  'video' : IDL.Null,
  'visualArt' : IDL.Null,
  'writing' : IDL.Null,
});
export const SubmissionRecord = IDL.Record({
  'id' : IDL.Text,
  'discipline' : Discipline,
  'link' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Opt(IDL.Text),
  'marketingConsentAt' : IDL.Opt(IDL.Int),
  'marketingConsent' : IDL.Bool,
});
export const SubmissionError = IDL.Variant({
  'invalidInput' : IDL.Text,
  'notConfigured' : IDL.Text,
  'honeypot' : IDL.Null,
  'rateLimited' : IDL.Null,
  'outcallFailed' : IDL.Text,
  'invalidResponse' : IDL.Text,
});
export const Result_14 = IDL.Variant({
  'ok' : IDL.Vec(SubmissionRecord),
  'err' : SubmissionError,
});
export const UserRecord = IDL.Record({ 'grantedAt' : IDL.Int, 'role' : Role });
export const EmailError = IDL.Variant({
  'notConfigured' : IDL.Text,
  'notShippable' : IDL.Null,
  'notFound' : IDL.Null,
  'outcallFailed' : IDL.Text,
  'unauthorized' : IDL.Null,
  'invalidResponse' : IDL.Text,
});
export const Result_11 = IDL.Variant({ 'ok' : IDL.Null, 'err' : EmailError });
export const Result_13 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : CategoryError });
export const SubmissionInput = IDL.Record({
  'discipline' : Discipline,
  'link' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Opt(IDL.Text),
  'honeypot' : IDL.Text,
  'marketingConsentAt' : IDL.Opt(IDL.Int),
  'marketingConsent' : IDL.Bool,
});
export const Result_9 = IDL.Variant({
  'ok' : IDL.Null,
  'err' : SubmissionError,
});
export const Result_8 = IDL.Variant({
  'ok' : IDL.Nat,
  'err' : CryptoPaymentError,
});
export const SweepSubaccountResult = IDL.Record({
  'error' : IDL.Opt(IDL.Text),
  'blockIndex' : IDL.Opt(IDL.Nat),
  'subaccountHex' : IDL.Text,
  'subaccountIndex' : IDL.Nat,
});
export const Result_6 = IDL.Variant({
  'ok' : SweepSubaccountResult,
  'err' : SweepError,
});
export const Result_5 = IDL.Variant({ 'ok' : IDL.Null, 'err' : ConsentError });
export const Result_3 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Result_1 = IDL.Variant({
  'ok' : IDL.Null,
  'err' : CryptoPaymentError,
});

export const idlService = IDL.Service({
  'addAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'adminCount' : IDL.Func([], [IDL.Nat], ['query']),
  'adminGetOrderDetail' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AdminOrderDetail)],
      ['query'],
    ),
  'adminListOrders' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AdminOrderView)],
      ['query'],
    ),
  'bootstrapOwner' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'cancelCardOrder' : IDL.Func([IDL.Text], [Result_2], []),
  'cancelGuestOrder' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
  'checkCryptoPayment' : IDL.Func([IDL.Text], [Result_19], []),
  'claimInitialAdmin' : IDL.Func([], [IDL.Bool], []),
  'confirmCardPayment' : IDL.Func([IDL.Text], [Result_26], []),
  'consentServiceTransform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'createCardCheckoutSession' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Result_25],
      [],
    ),
  'createCategory' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [Result_4], []),
  'createCheckoutSession' : IDL.Func([Order], [Result_24], []),
  'createOrder' : IDL.Func([CreateOrderInput], [Result_23], []),
  'createProduct' : IDL.Func([Product], [IDL.Bool], []),
  'deleteCategory' : IDL.Func([CategoryId], [Result_12], []),
  'deleteProductImage' : IDL.Func([IDL.Text], [Result], []),
  'emailTransform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'finishUpload' : IDL.Func([IDL.Text, IDL.Nat], [Result_10], []),
  'forceRecheckPayment' : IDL.Func([IDL.Text], [Result_22], []),
  'forceSweepOrder' : IDL.Func([IDL.Text], [Result_7], []),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCanisterId' : IDL.Func([], [IDL.Principal], ['query']),
  'getConsentListCsv' : IDL.Func([], [Result_21], []),
  'getCryptoConfig' : IDL.Func([], [CryptoConfigView], ['query']),
  'getCryptoDepositInfo' : IDL.Func([IDL.Text], [Result_20], ['query']),
  'getCryptoPaymentStatus' : IDL.Func([IDL.Text], [Result_19], ['query']),
  'getCycleBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getDashboardData' : IDL.Func([], [IDL.Text], []),
  'getDefaultSubaccountBalance' : IDL.Func([], [Result_18], []),
  'getEncryptionRecipients' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getFeaturedVideo' : IDL.Func(
      [],
      [IDL.Record({ 'rawUrl' : IDL.Text, 'embedUrl' : IDL.Text })],
      ['query'],
    ),
  'getIbePublicKey' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'getMinimumOrder' : IDL.Func([], [IDL.Nat], ['query']),
  'getMyEncryptedIbeKey' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Vec(IDL.Nat8)],
      [],
    ),
  'getMyOrders' : IDL.Func([], [IDL.Vec(PublicOrderView)], ['query']),
  'getMyRole' : IDL.Func([], [IDL.Opt(Role)], ['query']),
  'getNAKPrice' : IDL.Func([], [IDL.Text], []),
  'getOrderStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PublicOrderView)],
      ['query'],
    ),
  'getPaymentServiceConfig' : IDL.Func(
      [],
      [PaymentServiceConfigView],
      ['query'],
    ),
  'getPaymentStatus' : IDL.Func([IDL.Text], [PaymentStatus], []),
  'getPendingOrderConfig' : IDL.Func(
      [],
      [IDL.Record({ 'globalCap' : IDL.Nat, 'perSessionCap' : IDL.Nat })],
      ['query'],
    ),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getProductImageStorageStats' : IDL.Func([], [StorageStats], ['query']),
  'getResumeInfo' : IDL.Func([IDL.Text], [Result_17], ['query']),
  'getSubaccountBalance' : IDL.Func([IDL.Nat], [Result_16], []),
  'getTokenImage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'getTokenProfile' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'getTreasuryTokens' : IDL.Func([], [IDL.Text], []),
  'grantRole' : IDL.Func([IDL.Principal, Role], [IDL.Bool], []),
  'handlePaymentConfirmation' : IDL.Func([IDL.Text], [Result_15], []),
  'http_request' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
  'http_request_streaming_callback' : IDL.Func(
      [StreamingCallbackToken],
      [StreamingCallbackResponse],
      ['query'],
    ),
  'http_request_update' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], []),
  'listCategories' : IDL.Func([], [IDL.Vec(CategoryWithCount)], ['query']),
  'listLatePayments' : IDL.Func([], [IDL.Vec(LatePayment)], []),
  'listOrdersForRecovery' : IDL.Func([], [IDL.Vec(OrderRecoveryView)], []),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listSubmissions' : IDL.Func([], [Result_14], []),
  'listUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserRecord))],
      [],
    ),
  'markLatePaymentReviewed' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'markOrderShipped' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [Result_11], []),
  'paymentServiceTransform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'reassignProducts' : IDL.Func([IDL.Text, IDL.Text], [Result_13], []),
  'releaseExpiredOrders' : IDL.Func([], [IDL.Nat], []),
  'releaseExpiredReservations' : IDL.Func([], [IDL.Nat], []),
  'removeAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'reorderCategories' : IDL.Func([IDL.Vec(CategoryId)], [Result_12], []),
  'resendConfirmationEmail' : IDL.Func([IDL.Text], [Result_11], []),
  'resetAdminForMigration' : IDL.Func([], [IDL.Bool], []),
  'revokeRole' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'startUpload' : IDL.Func([IDL.Text, IDL.Nat], [Result_10], []),
  'startVerificationTimer' : IDL.Func([], [IDL.Bool], []),
  'stopVerificationTimer' : IDL.Func([], [IDL.Bool], []),
  'submissionServiceTransform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'submitSubmission' : IDL.Func([SubmissionInput], [Result_9], []),
  'sweepCryptoToTreasury' : IDL.Func([IDL.Text], [Result_8], []),
  'sweepDefaultSubaccount' : IDL.Func([], [Result_7], []),
  'sweepExpiredUploads' : IDL.Func([], [], []),
  'sweepSubaccount' : IDL.Func([IDL.Nat], [Result_6], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unsubscribe' : IDL.Func([IDL.Text], [Result_5], []),
  'updateCategory' : IDL.Func(
      [CategoryId, IDL.Text, IDL.Opt(IDL.Text), IDL.Nat, IDL.Bool, IDL.Bool],
      [Result_4],
      [],
    ),
  'updateFeaturedVideo' : IDL.Func([IDL.Text], [Result_3], []),
  'updateLedgerConfig' : IDL.Func(
      [Token, IDL.Principal, IDL.Nat8, IDL.Nat],
      [Result_1],
      [],
    ),
  'updateMinimumOrder' : IDL.Func([IDL.Nat], [Result_1], []),
  'updatePaymentServiceToken' : IDL.Func([IDL.Text], [Result_2], []),
  'updatePaymentServiceUrl' : IDL.Func([IDL.Text], [Result_2], []),
  'updatePendingOrderGlobalCap' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'updateProduct' : IDL.Func([Product], [IDL.Bool], []),
  'updateTreasury' : IDL.Func(
      [IDL.Principal, IDL.Opt(IDL.Vec(IDL.Nat8))],
      [Result_1],
      [],
    ),
  'uploadChunk' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Vec(IDL.Nat8)],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PaymentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'expired' : IDL.Null,
    'pending' : IDL.Null,
    'paid' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'crypto_icp' : IDL.Null,
    'card_stripe' : IDL.Null,
    'crypto_ckusdc' : IDL.Null,
    'manual' : IDL.Null,
  });
  const CryptoPaymentStatus = IDL.Variant({
    'overpayment' : IDL.Record({ 'expected' : IDL.Nat, 'received' : IDL.Nat }),
    'expired' : IDL.Null,
    'underpayment' : IDL.Record({ 'expected' : IDL.Nat, 'received' : IDL.Nat }),
    'paid' : IDL.Record({ 'blockIndex' : IDL.Nat }),
    'awaiting_payment' : IDL.Null,
  });
  const ProductId = IDL.Nat;
  const OrderItem = IDL.Record({
    'product_id' : ProductId,
    'unit_amount' : IDL.Nat,
    'name' : IDL.Text,
    'variant_id' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const AdminOrderDetail = IDL.Record({
    'status' : PaymentStatus,
    'paymentMethod' : PaymentMethod,
    'encryptedShipping' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'cryptoStatus' : IDL.Opt(CryptoPaymentStatus),
    'createdAt' : IDL.Int,
    'reference' : IDL.Text,
    'amountOwed' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'currency' : IDL.Text,
    'hasShippingDetails' : IDL.Bool,
    'subaccountHex' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'sweepNote' : IDL.Opt(IDL.Text),
    'customerEmail' : IDL.Text,
    'depositAccountText' : IDL.Text,
  });
  const AdminOrderView = IDL.Record({
    'status' : PaymentStatus,
    'paymentMethod' : PaymentMethod,
    'cryptoStatus' : IDL.Opt(CryptoPaymentStatus),
    'createdAt' : IDL.Int,
    'itemCount' : IDL.Nat,
    'reference' : IDL.Text,
    'amountOwed' : IDL.Nat,
    'currency' : IDL.Text,
    'subaccountHex' : IDL.Text,
    'sweepNote' : IDL.Opt(IDL.Text),
    'customerEmail' : IDL.Text,
    'depositAccountText' : IDL.Text,
  });
  const PaymentServiceError = IDL.Variant({
    'alreadyPaid' : IDL.Null,
    'notConfigured' : IDL.Text,
    'notFound' : IDL.Null,
    'rateLimited' : IDL.Null,
    'outcallFailed' : IDL.Text,
    'unauthorized' : IDL.Null,
    'invalidResponse' : IDL.Text,
  });
  const Result_2 = IDL.Variant({
    'ok' : IDL.Null,
    'err' : PaymentServiceError,
  });
  const CryptoPaymentError = IDL.Variant({
    'alreadyPaid' : IDL.Null,
    'overpayment' : IDL.Record({ 'expected' : IDL.Nat, 'received' : IDL.Nat }),
    'expired' : IDL.Null,
    'underpayment' : IDL.Record({ 'expected' : IDL.Nat, 'received' : IDL.Nat }),
    'sweepFailed' : IDL.Text,
    'notFound' : IDL.Null,
    'ledgerError' : IDL.Text,
    'notCryptoOrder' : IDL.Null,
    'unauthorized' : IDL.Null,
    'invalidConfig' : IDL.Text,
    'belowMinimumOrder' : IDL.Nat,
  });
  const Result_19 = IDL.Variant({
    'ok' : CryptoPaymentStatus,
    'err' : CryptoPaymentError,
  });
  const Result_26 = IDL.Variant({
    'ok' : PaymentStatus,
    'err' : PaymentServiceError,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const CheckoutSession = IDL.Record({
    'url' : IDL.Opt(IDL.Text),
    'reference' : IDL.Text,
  });
  const Result_25 = IDL.Variant({
    'ok' : CheckoutSession,
    'err' : PaymentServiceError,
  });
  const CategoryId = IDL.Nat;
  const Category = IDL.Record({
    'id' : CategoryId,
    'updated_at' : IDL.Int,
    'active' : IDL.Bool,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'created_at' : IDL.Int,
    'showWhenEmpty' : IDL.Bool,
  });
  const CategoryError = IDL.Variant({
    'emptyName' : IDL.Null,
    'targetCategoryNotFound' : IDL.Text,
    'notFound' : CategoryId,
    'productsReferenced' : IDL.Record({ 'count' : IDL.Nat, 'slug' : IDL.Text }),
    'slugCollision' : IDL.Text,
  });
  const Result_4 = IDL.Variant({ 'ok' : Category, 'err' : CategoryError });
  const ShippingStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'pending' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'tax' : IDL.Nat,
    'updated_at' : IDL.Int,
    'total' : IDL.Nat,
    'sweep_note' : IDL.Opt(IDL.Text),
    'shipping' : IDL.Nat,
    'reference' : IDL.Text,
    'created_at' : IDL.Int,
    'payment_status' : PaymentStatus,
    'payment_method' : PaymentMethod,
    'tracking_number' : IDL.Opt(IDL.Text),
    'currency' : IDL.Text,
    'marketing_consent_at' : IDL.Opt(IDL.Int),
    'shipping_status' : ShippingStatus,
    'has_shipping_details' : IDL.Bool,
    'items' : IDL.Vec(OrderItem),
    'customer_email' : IDL.Text,
    'encrypted_shipping' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'customer_principal' : IDL.Opt(IDL.Principal),
    'shipped_at' : IDL.Opt(IDL.Int),
    'marketing_consent' : IDL.Bool,
    'payment_reference' : IDL.Opt(IDL.Text),
    'subtotal' : IDL.Nat,
  });
  const PaymentError = IDL.Variant({
    'invalidOrder' : IDL.Null,
    'paymentFailed' : IDL.Text,
  });
  const Result_24 = IDL.Variant({
    'ok' : CheckoutSession,
    'err' : PaymentError,
  });
  const CreateOrderItem = IDL.Record({
    'product_id' : ProductId,
    'variant_id' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const CreateOrderInput = IDL.Record({
    'session_id' : IDL.Opt(IDL.Text),
    'payment_method' : PaymentMethod,
    'has_shipping_details' : IDL.Bool,
    'items' : IDL.Vec(CreateOrderItem),
    'customer_email' : IDL.Text,
    'encrypted_shipping' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'marketing_consent' : IDL.Bool,
  });
  const CreateOrderResult = IDL.Record({
    'order' : Order,
    'cancellationToken' : IDL.Opt(IDL.Text),
    'sessionId' : IDL.Opt(IDL.Text),
  });
  const OrderError = IDL.Variant({
    'outOfStock' : IDL.Tuple(ProductId, IDL.Text),
    'invalidPrice' : IDL.Text,
    'unknownVariant' : IDL.Tuple(ProductId, IDL.Text),
    'unknownProduct' : ProductId,
    'ckUSDCDisabled' : IDL.Null,
    'emptyOrder' : IDL.Null,
    'rateLimited' : IDL.Null,
    'belowMinimumOrder' : IDL.Nat,
    'productInactive' : ProductId,
    'paymentFailed' : IDL.Text,
    'invalidQuantity' : IDL.Null,
    'tooManyPendingOrders' : IDL.Null,
  });
  const Result_23 = IDL.Variant({
    'ok' : CreateOrderResult,
    'err' : OrderError,
  });
  const ProductVariant = IDL.Record({
    'id' : IDL.Text,
    'inventory' : IDL.Nat,
    'name' : IDL.Text,
    'size' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'updated_at' : IDL.Int,
    'active' : IDL.Bool,
    'inventory' : IDL.Nat,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'variants' : IDL.Vec(ProductVariant),
    'created_at' : IDL.Int,
    'currency' : IDL.Text,
    'admin_only' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  const Result_12 = IDL.Variant({ 'ok' : IDL.Null, 'err' : CategoryError });
  const UploadError = IDL.Variant({
    'tooManyImages' : IDL.Null,
    'tooLarge' : IDL.Null,
    'magicByteMismatch' : IDL.Null,
    'sizeMismatch' : IDL.Null,
    'invalidContentType' : IDL.Null,
    'notFound' : IDL.Null,
    'uploadExpired' : IDL.Null,
    'svgNotAllowed' : IDL.Null,
    'chunkOutOfOrder' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : UploadError });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const Result_10 = IDL.Variant({ 'ok' : IDL.Text, 'err' : UploadError });
  const RecheckResult = IDL.Record({
    'status' : CryptoPaymentStatus,
    'balance' : IDL.Nat,
    'reference' : IDL.Text,
    'error' : IDL.Opt(IDL.Text),
  });
  const RecoveryError = IDL.Variant({
    'sweepFailed' : IDL.Text,
    'notFound' : IDL.Null,
    'ledgerError' : IDL.Text,
    'notCryptoOrder' : IDL.Null,
    'unauthorized' : IDL.Null,
    'invalidConfig' : IDL.Text,
  });
  const Result_22 = IDL.Variant({
    'ok' : RecheckResult,
    'err' : RecoveryError,
  });
  const SweepResult = IDL.Record({
    'reference' : IDL.Opt(IDL.Text),
    'error' : IDL.Opt(IDL.Text),
    'blockIndex' : IDL.Opt(IDL.Nat),
  });
  const Result_7 = IDL.Variant({ 'ok' : SweepResult, 'err' : RecoveryError });
  const ConsentListExport = IDL.Record({ 'csv' : IDL.Text });
  const ConsentError = IDL.Variant({
    'alreadyUnsubscribed' : IDL.Null,
    'notConfigured' : IDL.Text,
    'invalidToken' : IDL.Null,
    'rateLimited' : IDL.Null,
    'outcallFailed' : IDL.Text,
    'unauthorized' : IDL.Null,
    'invalidResponse' : IDL.Text,
  });
  const Result_21 = IDL.Variant({
    'ok' : ConsentListExport,
    'err' : ConsentError,
  });
  const LedgerConfig = IDL.Record({
    'fee' : IDL.Nat,
    'decimals' : IDL.Nat8,
    'canisterId' : IDL.Principal,
  });
  const CryptoConfigView = IDL.Record({
    'icp' : LedgerConfig,
    'ckUSDC' : LedgerConfig,
    'treasurySubaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'minimumOrder' : IDL.Nat,
    'ckUSDCEnabled' : IDL.Bool,
    'treasuryPrincipal' : IDL.Principal,
  });
  const Token = IDL.Variant({ 'ICP' : IDL.Null, 'ckUSDC' : IDL.Null });
  const DepositInfo = IDL.Record({
    'decimals' : IDL.Nat8,
    'token' : Token,
    'expiresAt' : IDL.Int,
    'qrPayload' : IDL.Text,
    'subaccount' : IDL.Vec(IDL.Nat8),
    'reference' : IDL.Text,
    'address' : IDL.Principal,
    'amountDue' : IDL.Nat,
  });
  const Result_20 = IDL.Variant({
    'ok' : DepositInfo,
    'err' : CryptoPaymentError,
  });
  const Result_18 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : RecoveryError });
  const PublicOrderView = IDL.Record({
    'id' : IDL.Nat,
    'tax' : IDL.Float64,
    'updated_at' : IDL.Int,
    'total' : IDL.Float64,
    'sweep_note' : IDL.Opt(IDL.Text),
    'shipping' : IDL.Float64,
    'reference' : IDL.Text,
    'created_at' : IDL.Int,
    'payment_status' : PaymentStatus,
    'payment_method' : PaymentMethod,
    'tracking_number' : IDL.Opt(IDL.Text),
    'currency' : IDL.Text,
    'marketing_consent_at' : IDL.Opt(IDL.Int),
    'shipping_status' : ShippingStatus,
    'has_shipping_details' : IDL.Bool,
    'items' : IDL.Vec(OrderItem),
    'encrypted_shipping' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'customer_principal' : IDL.Opt(IDL.Principal),
    'shipped_at' : IDL.Opt(IDL.Int),
    'marketing_consent' : IDL.Bool,
    'payment_reference' : IDL.Opt(IDL.Text),
    'subtotal' : IDL.Float64,
  });
  const Role = IDL.Variant({
    'admin' : IDL.Null,
    'owner' : IDL.Null,
    'staff' : IDL.Null,
  });
  const PaymentServiceConfigView = IDL.Record({
    'url' : IDL.Text,
    'tokenSet' : IDL.Bool,
  });
  const StorageStats = IDL.Record({
    'count' : IDL.Nat,
    'totalBytes' : IDL.Nat,
  });
  const ResumeInfo = IDL.Record({
    'status' : CryptoPaymentStatus,
    'expiresAt' : IDL.Int,
    'reference' : IDL.Text,
    'deposit' : IDL.Opt(DepositInfo),
    'remainingNs' : IDL.Int,
  });
  const Result_17 = IDL.Variant({ 'ok' : ResumeInfo, 'err' : RecoveryError });
  const SubaccountBalanceResult = IDL.Record({
    'balance' : IDL.Nat,
    'subaccountHex' : IDL.Text,
    'subaccountIndex' : IDL.Nat,
  });
  const SweepError = IDL.Variant({
    'sweepFailed' : IDL.Text,
    'ledgerError' : IDL.Text,
    'unauthorized' : IDL.Null,
    'invalidConfig' : IDL.Text,
  });
  const Result_16 = IDL.Variant({
    'ok' : SubaccountBalanceResult,
    'err' : SweepError,
  });
  const Result_15 = IDL.Variant({ 'ok' : IDL.Null, 'err' : PaymentError });
  const HttpRequest = IDL.Record({
    'url' : IDL.Text,
    'method' : IDL.Text,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  });
  const StreamingCallbackToken = IDL.Record({
    'key' : IDL.Text,
    'sha256' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'index' : IDL.Nat,
    'content_encoding' : IDL.Text,
  });
  const StreamingCallbackResponse = IDL.Record({
    'token' : IDL.Opt(StreamingCallbackToken),
    'body' : IDL.Vec(IDL.Nat8),
  });
  const StreamingCallback = IDL.Func(
      [StreamingCallbackToken],
      [StreamingCallbackResponse],
      ['query'],
    );
  const StreamingStrategy = IDL.Variant({
    'Callback' : IDL.Record({
      'token' : StreamingCallbackToken,
      'callback' : StreamingCallback,
    }),
  });
  const HttpResponse = IDL.Record({
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'streaming_strategy' : IDL.Opt(StreamingStrategy),
    'status_code' : IDL.Nat16,
  });
  const CategoryWithCount = IDL.Record({
    'productCount' : IDL.Nat,
    'category' : Category,
  });
  const LatePayment = IDL.Record({
    'token' : Token,
    'reference' : IDL.Text,
    'receivedAmount' : IDL.Nat,
    'receivedAt' : IDL.Int,
    'reviewed' : IDL.Bool,
    'expectedAmount' : IDL.Nat,
  });
  const DepositAccount = IDL.Record({
    'owner' : IDL.Principal,
    'subaccount' : IDL.Vec(IDL.Nat8),
    'textAddress' : IDL.Text,
  });
  const OrderRecoveryView = IDL.Record({
    'status' : PaymentStatus,
    'paymentMethod' : PaymentMethod,
    'expiresAt' : IDL.Opt(IDL.Int),
    'reference' : IDL.Text,
    'depositAccount' : IDL.Opt(DepositAccount),
    'amountOwed' : IDL.Nat,
    'liveBalance' : IDL.Nat,
  });
  const Discipline = IDL.Variant({
    'music' : IDL.Null,
    'other' : IDL.Null,
    'video' : IDL.Null,
    'visualArt' : IDL.Null,
    'writing' : IDL.Null,
  });
  const SubmissionRecord = IDL.Record({
    'id' : IDL.Text,
    'discipline' : Discipline,
    'link' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Opt(IDL.Text),
    'marketingConsentAt' : IDL.Opt(IDL.Int),
    'marketingConsent' : IDL.Bool,
  });
  const SubmissionError = IDL.Variant({
    'invalidInput' : IDL.Text,
    'notConfigured' : IDL.Text,
    'honeypot' : IDL.Null,
    'rateLimited' : IDL.Null,
    'outcallFailed' : IDL.Text,
    'invalidResponse' : IDL.Text,
  });
  const Result_14 = IDL.Variant({
    'ok' : IDL.Vec(SubmissionRecord),
    'err' : SubmissionError,
  });
  const UserRecord = IDL.Record({ 'grantedAt' : IDL.Int, 'role' : Role });
  const EmailError = IDL.Variant({
    'notConfigured' : IDL.Text,
    'notShippable' : IDL.Null,
    'notFound' : IDL.Null,
    'outcallFailed' : IDL.Text,
    'unauthorized' : IDL.Null,
    'invalidResponse' : IDL.Text,
  });
  const Result_11 = IDL.Variant({ 'ok' : IDL.Null, 'err' : EmailError });
  const Result_13 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : CategoryError });
  const SubmissionInput = IDL.Record({
    'discipline' : Discipline,
    'link' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Opt(IDL.Text),
    'honeypot' : IDL.Text,
    'marketingConsentAt' : IDL.Opt(IDL.Int),
    'marketingConsent' : IDL.Bool,
  });
  const Result_9 = IDL.Variant({ 'ok' : IDL.Null, 'err' : SubmissionError });
  const Result_8 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : CryptoPaymentError });
  const SweepSubaccountResult = IDL.Record({
    'error' : IDL.Opt(IDL.Text),
    'blockIndex' : IDL.Opt(IDL.Nat),
    'subaccountHex' : IDL.Text,
    'subaccountIndex' : IDL.Nat,
  });
  const Result_6 = IDL.Variant({
    'ok' : SweepSubaccountResult,
    'err' : SweepError,
  });
  const Result_5 = IDL.Variant({ 'ok' : IDL.Null, 'err' : ConsentError });
  const Result_3 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : CryptoPaymentError });
  
  return IDL.Service({
    'addAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'adminCount' : IDL.Func([], [IDL.Nat], ['query']),
    'adminGetOrderDetail' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AdminOrderDetail)],
        ['query'],
      ),
    'adminListOrders' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AdminOrderView)],
        ['query'],
      ),
    'bootstrapOwner' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'cancelCardOrder' : IDL.Func([IDL.Text], [Result_2], []),
    'cancelGuestOrder' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
    'checkCryptoPayment' : IDL.Func([IDL.Text], [Result_19], []),
    'claimInitialAdmin' : IDL.Func([], [IDL.Bool], []),
    'confirmCardPayment' : IDL.Func([IDL.Text], [Result_26], []),
    'consentServiceTransform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'createCardCheckoutSession' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Result_25],
        [],
      ),
    'createCategory' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [Result_4], []),
    'createCheckoutSession' : IDL.Func([Order], [Result_24], []),
    'createOrder' : IDL.Func([CreateOrderInput], [Result_23], []),
    'createProduct' : IDL.Func([Product], [IDL.Bool], []),
    'deleteCategory' : IDL.Func([CategoryId], [Result_12], []),
    'deleteProductImage' : IDL.Func([IDL.Text], [Result], []),
    'emailTransform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'finishUpload' : IDL.Func([IDL.Text, IDL.Nat], [Result_10], []),
    'forceRecheckPayment' : IDL.Func([IDL.Text], [Result_22], []),
    'forceSweepOrder' : IDL.Func([IDL.Text], [Result_7], []),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCanisterId' : IDL.Func([], [IDL.Principal], ['query']),
    'getConsentListCsv' : IDL.Func([], [Result_21], []),
    'getCryptoConfig' : IDL.Func([], [CryptoConfigView], ['query']),
    'getCryptoDepositInfo' : IDL.Func([IDL.Text], [Result_20], ['query']),
    'getCryptoPaymentStatus' : IDL.Func([IDL.Text], [Result_19], ['query']),
    'getCycleBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getDashboardData' : IDL.Func([], [IDL.Text], []),
    'getDefaultSubaccountBalance' : IDL.Func([], [Result_18], []),
    'getEncryptionRecipients' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFeaturedVideo' : IDL.Func(
        [],
        [IDL.Record({ 'rawUrl' : IDL.Text, 'embedUrl' : IDL.Text })],
        ['query'],
      ),
    'getIbePublicKey' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'getMinimumOrder' : IDL.Func([], [IDL.Nat], ['query']),
    'getMyEncryptedIbeKey' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Vec(IDL.Nat8)],
        [],
      ),
    'getMyOrders' : IDL.Func([], [IDL.Vec(PublicOrderView)], ['query']),
    'getMyRole' : IDL.Func([], [IDL.Opt(Role)], ['query']),
    'getNAKPrice' : IDL.Func([], [IDL.Text], []),
    'getOrderStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PublicOrderView)],
        ['query'],
      ),
    'getPaymentServiceConfig' : IDL.Func(
        [],
        [PaymentServiceConfigView],
        ['query'],
      ),
    'getPaymentStatus' : IDL.Func([IDL.Text], [PaymentStatus], []),
    'getPendingOrderConfig' : IDL.Func(
        [],
        [IDL.Record({ 'globalCap' : IDL.Nat, 'perSessionCap' : IDL.Nat })],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getProductImageStorageStats' : IDL.Func([], [StorageStats], ['query']),
    'getResumeInfo' : IDL.Func([IDL.Text], [Result_17], ['query']),
    'getSubaccountBalance' : IDL.Func([IDL.Nat], [Result_16], []),
    'getTokenImage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'getTokenProfile' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'getTreasuryTokens' : IDL.Func([], [IDL.Text], []),
    'grantRole' : IDL.Func([IDL.Principal, Role], [IDL.Bool], []),
    'handlePaymentConfirmation' : IDL.Func([IDL.Text], [Result_15], []),
    'http_request' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
    'http_request_streaming_callback' : IDL.Func(
        [StreamingCallbackToken],
        [StreamingCallbackResponse],
        ['query'],
      ),
    'http_request_update' : IDL.Func([HttpRequest], [HttpResponse], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAdmins' : IDL.Func([], [IDL.Vec(IDL.Principal)], []),
    'listCategories' : IDL.Func([], [IDL.Vec(CategoryWithCount)], ['query']),
    'listLatePayments' : IDL.Func([], [IDL.Vec(LatePayment)], []),
    'listOrdersForRecovery' : IDL.Func([], [IDL.Vec(OrderRecoveryView)], []),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listSubmissions' : IDL.Func([], [Result_14], []),
    'listUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserRecord))],
        [],
      ),
    'markLatePaymentReviewed' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'markOrderShipped' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [Result_11],
        [],
      ),
    'paymentServiceTransform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'reassignProducts' : IDL.Func([IDL.Text, IDL.Text], [Result_13], []),
    'releaseExpiredOrders' : IDL.Func([], [IDL.Nat], []),
    'releaseExpiredReservations' : IDL.Func([], [IDL.Nat], []),
    'removeAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'reorderCategories' : IDL.Func([IDL.Vec(CategoryId)], [Result_12], []),
    'resendConfirmationEmail' : IDL.Func([IDL.Text], [Result_11], []),
    'resetAdminForMigration' : IDL.Func([], [IDL.Bool], []),
    'revokeRole' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'startUpload' : IDL.Func([IDL.Text, IDL.Nat], [Result_10], []),
    'startVerificationTimer' : IDL.Func([], [IDL.Bool], []),
    'stopVerificationTimer' : IDL.Func([], [IDL.Bool], []),
    'submissionServiceTransform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'submitSubmission' : IDL.Func([SubmissionInput], [Result_9], []),
    'sweepCryptoToTreasury' : IDL.Func([IDL.Text], [Result_8], []),
    'sweepDefaultSubaccount' : IDL.Func([], [Result_7], []),
    'sweepExpiredUploads' : IDL.Func([], [], []),
    'sweepSubaccount' : IDL.Func([IDL.Nat], [Result_6], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unsubscribe' : IDL.Func([IDL.Text], [Result_5], []),
    'updateCategory' : IDL.Func(
        [CategoryId, IDL.Text, IDL.Opt(IDL.Text), IDL.Nat, IDL.Bool, IDL.Bool],
        [Result_4],
        [],
      ),
    'updateFeaturedVideo' : IDL.Func([IDL.Text], [Result_3], []),
    'updateLedgerConfig' : IDL.Func(
        [Token, IDL.Principal, IDL.Nat8, IDL.Nat],
        [Result_1],
        [],
      ),
    'updateMinimumOrder' : IDL.Func([IDL.Nat], [Result_1], []),
    'updatePaymentServiceToken' : IDL.Func([IDL.Text], [Result_2], []),
    'updatePaymentServiceUrl' : IDL.Func([IDL.Text], [Result_2], []),
    'updatePendingOrderGlobalCap' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'updateProduct' : IDL.Func([Product], [IDL.Bool], []),
    'updateTreasury' : IDL.Func(
        [IDL.Principal, IDL.Opt(IDL.Vec(IDL.Nat8))],
        [Result_1],
        [],
      ),
    'uploadChunk' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Vec(IDL.Nat8)],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };