/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export interface CheckoutSession { 'url' : [] | [string], 'reference' : string }
export interface CreateOrderInput {
  'shipping_address' : ShippingAddress,
  'payment_method' : PaymentMethod,
  'items' : Array<CreateOrderItem>,
  'customer_email' : string,
  'customer_name' : string,
}
export interface CreateOrderItem {
  'product_id' : ProductId,
  'variant_id' : string,
  'quantity' : bigint,
}
export interface CryptoConfigView {
  'icp' : LedgerConfig,
  'ckUSDC' : LedgerConfig,
  'treasurySubaccount' : [] | [Uint8Array],
  'treasuryPrincipal' : Principal,
}
export type CryptoPaymentError = { 'alreadyPaid' : null } |
  { 'overpayment' : { 'expected' : bigint, 'received' : bigint } } |
  { 'expired' : null } |
  { 'underpayment' : { 'expected' : bigint, 'received' : bigint } } |
  { 'sweepFailed' : string } |
  { 'notFound' : null } |
  { 'ledgerError' : string } |
  { 'notCryptoOrder' : null } |
  { 'unauthorized' : null } |
  { 'invalidConfig' : string };
export type CryptoPaymentStatus = {
    'overpayment' : { 'expected' : bigint, 'received' : bigint }
  } |
  { 'expired' : null } |
  { 'underpayment' : { 'expected' : bigint, 'received' : bigint } } |
  { 'paid' : { 'blockIndex' : bigint } } |
  { 'awaiting_payment' : null };
export interface DepositInfo {
  'decimals' : number,
  'token' : Token,
  'expiresAt' : bigint,
  'qrPayload' : string,
  'subaccount' : Uint8Array,
  'reference' : string,
  'address' : Principal,
  'amountDue' : bigint,
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface LedgerConfig {
  'fee' : bigint,
  'decimals' : number,
  'canisterId' : Principal,
}
export interface Order {
  'id' : bigint,
  'tax' : bigint,
  'updated_at' : bigint,
  'total' : bigint,
  'shipping_address' : ShippingAddress,
  'shipping' : bigint,
  'reference' : string,
  'created_at' : bigint,
  'payment_status' : PaymentStatus,
  'payment_method' : PaymentMethod,
  'currency' : string,
  'items' : Array<OrderItem>,
  'customer_email' : string,
  'customer_name' : string,
  'payment_reference' : [] | [string],
  'subtotal' : bigint,
}
export type OrderError = { 'outOfStock' : [ProductId, string] } |
  { 'unknownVariant' : [ProductId, string] } |
  { 'unknownProduct' : ProductId } |
  { 'emptyOrder' : null } |
  { 'productInactive' : ProductId } |
  { 'paymentFailed' : string } |
  { 'invalidQuantity' : null };
export interface OrderItem {
  'product_id' : ProductId,
  'unit_amount' : bigint,
  'name' : string,
  'variant_id' : string,
  'quantity' : bigint,
}
export type PaymentError = { 'invalidOrder' : null } |
  { 'paymentFailed' : string };
export type PaymentMethod = { 'crypto_icp' : null } |
  { 'card_stripe' : null } |
  { 'crypto_ckusdc' : null } |
  { 'manual' : null };
export type PaymentStatus = { 'cancelled' : null } |
  { 'expired' : null } |
  { 'pending' : null } |
  { 'paid' : null };
export interface Product {
  'id' : ProductId,
  'updated_at' : bigint,
  'active' : boolean,
  'inventory' : bigint,
  'name' : string,
  'slug' : string,
  'description' : string,
  'variants' : Array<ProductVariant>,
  'created_at' : bigint,
  'currency' : string,
  'category' : string,
  'price' : bigint,
  'images' : Array<string>,
}
export type ProductId = bigint;
export interface ProductVariant {
  'id' : string,
  'inventory' : bigint,
  'name' : string,
  'size' : string,
  'price' : bigint,
}
export type Result = { 'ok' : null } |
  { 'err' : CryptoPaymentError };
export type Result_1 = { 'ok' : bigint } |
  { 'err' : CryptoPaymentError };
export type Result_2 = { 'ok' : null } |
  { 'err' : PaymentError };
export type Result_3 = { 'ok' : CryptoPaymentStatus } |
  { 'err' : CryptoPaymentError };
export type Result_4 = { 'ok' : DepositInfo } |
  { 'err' : CryptoPaymentError };
export type Result_5 = { 'ok' : Order } |
  { 'err' : OrderError };
export type Result_6 = { 'ok' : CheckoutSession } |
  { 'err' : PaymentError };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface ShippingAddress {
  'region' : string,
  'country' : string,
  'city' : string,
  'postal_code' : string,
  'line1' : string,
  'line2' : [] | [string],
}
export type Token = { 'ICP' : null } |
  { 'ckUSDC' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  'checkCryptoPayment' : ActorMethod<[string], Result_3>,
  'confirmCryptoPayment' : ActorMethod<[string], Result_3>,
  'createCheckoutSession' : ActorMethod<[Order], Result_6>,
  'createOrder' : ActorMethod<[CreateOrderInput], Result_5>,
  'execute' : ActorMethod<[string], Result__1>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCryptoConfig' : ActorMethod<[], CryptoConfigView>,
  'getCryptoDepositInfo' : ActorMethod<[string], Result_4>,
  'getCryptoPaymentStatus' : ActorMethod<[string], Result_3>,
  'getDashboardData' : ActorMethod<[], string>,
  'getNAKPrice' : ActorMethod<[], string>,
  'getOrderStatus' : ActorMethod<[string], [] | [Order]>,
  'getPaymentStatus' : ActorMethod<[string], PaymentStatus>,
  'getProduct' : ActorMethod<[string], [] | [Product]>,
  'getTokenImage' : ActorMethod<[string, string], string>,
  'getTokenProfile' : ActorMethod<[string, string], string>,
  'getTreasuryTokens' : ActorMethod<[], string>,
  'handlePaymentConfirmation' : ActorMethod<[string], Result_2>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'releaseExpiredOrders' : ActorMethod<[], bigint>,
  'schema' : ActorMethod<[], string>,
  'sweepCryptoToTreasury' : ActorMethod<[string], Result_1>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateLedgerConfig' : ActorMethod<
    [Token, Principal, number, bigint],
    Result
  >,
  'updateTreasury' : ActorMethod<[Principal, [] | [Uint8Array]], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];