/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CryptoPaymentStatus = IDL.Variant({
  'overpayment' : IDL.Record({ 'expected' : IDL.Nat, 'received' : IDL.Nat }),
  'expired' : IDL.Null,
  'underpayment' : IDL.Record({ 'expected' : IDL.Nat, 'received' : IDL.Nat }),
  'paid' : IDL.Record({ 'blockIndex' : IDL.Nat }),
  'awaiting_payment' : IDL.Null,
});
export const CryptoPaymentError = IDL.Variant({
  'alreadyPaid' : IDL.Null,
  'overpayment' : IDL.Record({ 'expected' : IDL.Nat, 'received' : IDL.Nat }),
  'expired' : IDL.Null,
  'underpayment' : IDL.Record({ 'expected' : IDL.Nat, 'received' : IDL.Nat }),
  'sweepFailed' : IDL.Text,
  'notFound' : IDL.Null,
  'ledgerError' : IDL.Text,
  'notCryptoOrder' : IDL.Null,
  'unauthorized' : IDL.Null,
  'invalidConfig' : IDL.Text,
});
export const Result_3 = IDL.Variant({
  'ok' : CryptoPaymentStatus,
  'err' : CryptoPaymentError,
});
export const ShippingAddress = IDL.Record({
  'region' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'postal_code' : IDL.Text,
  'line1' : IDL.Text,
  'line2' : IDL.Opt(IDL.Text),
});
export const PaymentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'expired' : IDL.Null,
  'pending' : IDL.Null,
  'paid' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'crypto_icp' : IDL.Null,
  'card_stripe' : IDL.Null,
  'crypto_ckusdc' : IDL.Null,
  'manual' : IDL.Null,
});
export const ProductId = IDL.Nat;
export const OrderItem = IDL.Record({
  'product_id' : ProductId,
  'unit_amount' : IDL.Nat,
  'name' : IDL.Text,
  'variant_id' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'tax' : IDL.Nat,
  'updated_at' : IDL.Int,
  'total' : IDL.Nat,
  'shipping_address' : ShippingAddress,
  'shipping' : IDL.Nat,
  'reference' : IDL.Text,
  'created_at' : IDL.Int,
  'payment_status' : PaymentStatus,
  'payment_method' : PaymentMethod,
  'currency' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'customer_email' : IDL.Text,
  'customer_name' : IDL.Text,
  'payment_reference' : IDL.Opt(IDL.Text),
  'subtotal' : IDL.Nat,
});
export const CheckoutSession = IDL.Record({
  'url' : IDL.Opt(IDL.Text),
  'reference' : IDL.Text,
});
export const PaymentError = IDL.Variant({
  'invalidOrder' : IDL.Null,
  'paymentFailed' : IDL.Text,
});
export const Result_6 = IDL.Variant({
  'ok' : CheckoutSession,
  'err' : PaymentError,
});
export const CreateOrderItem = IDL.Record({
  'product_id' : ProductId,
  'variant_id' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const CreateOrderInput = IDL.Record({
  'shipping_address' : ShippingAddress,
  'payment_method' : PaymentMethod,
  'items' : IDL.Vec(CreateOrderItem),
  'customer_email' : IDL.Text,
  'customer_name' : IDL.Text,
});
export const OrderError = IDL.Variant({
  'outOfStock' : IDL.Tuple(ProductId, IDL.Text),
  'unknownVariant' : IDL.Tuple(ProductId, IDL.Text),
  'unknownProduct' : ProductId,
  'emptyOrder' : IDL.Null,
  'productInactive' : ProductId,
  'paymentFailed' : IDL.Text,
  'invalidQuantity' : IDL.Null,
});
export const Result_5 = IDL.Variant({ 'ok' : Order, 'err' : OrderError });
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const LedgerConfig = IDL.Record({
  'fee' : IDL.Nat,
  'decimals' : IDL.Nat8,
  'canisterId' : IDL.Principal,
});
export const CryptoConfigView = IDL.Record({
  'icp' : LedgerConfig,
  'ckUSDC' : LedgerConfig,
  'treasurySubaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'treasuryPrincipal' : IDL.Principal,
});
export const Token = IDL.Variant({ 'ICP' : IDL.Null, 'ckUSDC' : IDL.Null });
export const DepositInfo = IDL.Record({
  'decimals' : IDL.Nat8,
  'token' : Token,
  'expiresAt' : IDL.Int,
  'qrPayload' : IDL.Text,
  'subaccount' : IDL.Vec(IDL.Nat8),
  'reference' : IDL.Text,
  'address' : IDL.Principal,
  'amountDue' : IDL.Nat,
});
export const Result_4 = IDL.Variant({
  'ok' : DepositInfo,
  'err' : CryptoPaymentError,
});
export const ProductVariant = IDL.Record({
  'id' : IDL.Text,
  'inventory' : IDL.Nat,
  'name' : IDL.Text,
  'size' : IDL.Text,
  'price' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'updated_at' : IDL.Int,
  'active' : IDL.Bool,
  'inventory' : IDL.Nat,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'variants' : IDL.Vec(ProductVariant),
  'created_at' : IDL.Int,
  'currency' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});
export const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : PaymentError });
export const Result_1 = IDL.Variant({
  'ok' : IDL.Nat,
  'err' : CryptoPaymentError,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpRequestResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpRequestResult,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const Result = IDL.Variant({
  'ok' : IDL.Null,
  'err' : CryptoPaymentError,
});

export const idlService = IDL.Service({
  'checkCryptoPayment' : IDL.Func([IDL.Text], [Result_3], []),
  'confirmCryptoPayment' : IDL.Func([IDL.Text], [Result_3], []),
  'createCheckoutSession' : IDL.Func([Order], [Result_6], []),
  'createOrder' : IDL.Func([CreateOrderInput], [Result_5], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCryptoConfig' : IDL.Func([], [CryptoConfigView], ['query']),
  'getCryptoDepositInfo' : IDL.Func([IDL.Text], [Result_4], ['query']),
  'getCryptoPaymentStatus' : IDL.Func([IDL.Text], [Result_3], ['query']),
  'getDashboardData' : IDL.Func([], [IDL.Text], []),
  'getNAKPrice' : IDL.Func([], [IDL.Text], []),
  'getOrderStatus' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getPaymentStatus' : IDL.Func([IDL.Text], [PaymentStatus], []),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getTokenImage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'getTokenProfile' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'getTreasuryTokens' : IDL.Func([], [IDL.Text], []),
  'handlePaymentConfirmation' : IDL.Func([IDL.Text], [Result_2], []),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'releaseExpiredOrders' : IDL.Func([], [IDL.Nat], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'sweepCryptoToTreasury' : IDL.Func([IDL.Text], [Result_1], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateLedgerConfig' : IDL.Func(
      [Token, IDL.Principal, IDL.Nat8, IDL.Nat],
      [Result],
      [],
    ),
  'updateTreasury' : IDL.Func(
      [IDL.Principal, IDL.Opt(IDL.Vec(IDL.Nat8))],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CryptoPaymentStatus = IDL.Variant({
    'overpayment' : IDL.Record({ 'expected' : IDL.Nat, 'received' : IDL.Nat }),
    'expired' : IDL.Null,
    'underpayment' : IDL.Record({ 'expected' : IDL.Nat, 'received' : IDL.Nat }),
    'paid' : IDL.Record({ 'blockIndex' : IDL.Nat }),
    'awaiting_payment' : IDL.Null,
  });
  const CryptoPaymentError = IDL.Variant({
    'alreadyPaid' : IDL.Null,
    'overpayment' : IDL.Record({ 'expected' : IDL.Nat, 'received' : IDL.Nat }),
    'expired' : IDL.Null,
    'underpayment' : IDL.Record({ 'expected' : IDL.Nat, 'received' : IDL.Nat }),
    'sweepFailed' : IDL.Text,
    'notFound' : IDL.Null,
    'ledgerError' : IDL.Text,
    'notCryptoOrder' : IDL.Null,
    'unauthorized' : IDL.Null,
    'invalidConfig' : IDL.Text,
  });
  const Result_3 = IDL.Variant({
    'ok' : CryptoPaymentStatus,
    'err' : CryptoPaymentError,
  });
  const ShippingAddress = IDL.Record({
    'region' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'postal_code' : IDL.Text,
    'line1' : IDL.Text,
    'line2' : IDL.Opt(IDL.Text),
  });
  const PaymentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'expired' : IDL.Null,
    'pending' : IDL.Null,
    'paid' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'crypto_icp' : IDL.Null,
    'card_stripe' : IDL.Null,
    'crypto_ckusdc' : IDL.Null,
    'manual' : IDL.Null,
  });
  const ProductId = IDL.Nat;
  const OrderItem = IDL.Record({
    'product_id' : ProductId,
    'unit_amount' : IDL.Nat,
    'name' : IDL.Text,
    'variant_id' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'tax' : IDL.Nat,
    'updated_at' : IDL.Int,
    'total' : IDL.Nat,
    'shipping_address' : ShippingAddress,
    'shipping' : IDL.Nat,
    'reference' : IDL.Text,
    'created_at' : IDL.Int,
    'payment_status' : PaymentStatus,
    'payment_method' : PaymentMethod,
    'currency' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'customer_email' : IDL.Text,
    'customer_name' : IDL.Text,
    'payment_reference' : IDL.Opt(IDL.Text),
    'subtotal' : IDL.Nat,
  });
  const CheckoutSession = IDL.Record({
    'url' : IDL.Opt(IDL.Text),
    'reference' : IDL.Text,
  });
  const PaymentError = IDL.Variant({
    'invalidOrder' : IDL.Null,
    'paymentFailed' : IDL.Text,
  });
  const Result_6 = IDL.Variant({
    'ok' : CheckoutSession,
    'err' : PaymentError,
  });
  const CreateOrderItem = IDL.Record({
    'product_id' : ProductId,
    'variant_id' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const CreateOrderInput = IDL.Record({
    'shipping_address' : ShippingAddress,
    'payment_method' : PaymentMethod,
    'items' : IDL.Vec(CreateOrderItem),
    'customer_email' : IDL.Text,
    'customer_name' : IDL.Text,
  });
  const OrderError = IDL.Variant({
    'outOfStock' : IDL.Tuple(ProductId, IDL.Text),
    'unknownVariant' : IDL.Tuple(ProductId, IDL.Text),
    'unknownProduct' : ProductId,
    'emptyOrder' : IDL.Null,
    'productInactive' : ProductId,
    'paymentFailed' : IDL.Text,
    'invalidQuantity' : IDL.Null,
  });
  const Result_5 = IDL.Variant({ 'ok' : Order, 'err' : OrderError });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const LedgerConfig = IDL.Record({
    'fee' : IDL.Nat,
    'decimals' : IDL.Nat8,
    'canisterId' : IDL.Principal,
  });
  const CryptoConfigView = IDL.Record({
    'icp' : LedgerConfig,
    'ckUSDC' : LedgerConfig,
    'treasurySubaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'treasuryPrincipal' : IDL.Principal,
  });
  const Token = IDL.Variant({ 'ICP' : IDL.Null, 'ckUSDC' : IDL.Null });
  const DepositInfo = IDL.Record({
    'decimals' : IDL.Nat8,
    'token' : Token,
    'expiresAt' : IDL.Int,
    'qrPayload' : IDL.Text,
    'subaccount' : IDL.Vec(IDL.Nat8),
    'reference' : IDL.Text,
    'address' : IDL.Principal,
    'amountDue' : IDL.Nat,
  });
  const Result_4 = IDL.Variant({
    'ok' : DepositInfo,
    'err' : CryptoPaymentError,
  });
  const ProductVariant = IDL.Record({
    'id' : IDL.Text,
    'inventory' : IDL.Nat,
    'name' : IDL.Text,
    'size' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'updated_at' : IDL.Int,
    'active' : IDL.Bool,
    'inventory' : IDL.Nat,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'variants' : IDL.Vec(ProductVariant),
    'created_at' : IDL.Int,
    'currency' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : PaymentError });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : CryptoPaymentError });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : CryptoPaymentError });
  
  return IDL.Service({
    'checkCryptoPayment' : IDL.Func([IDL.Text], [Result_3], []),
    'confirmCryptoPayment' : IDL.Func([IDL.Text], [Result_3], []),
    'createCheckoutSession' : IDL.Func([Order], [Result_6], []),
    'createOrder' : IDL.Func([CreateOrderInput], [Result_5], []),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCryptoConfig' : IDL.Func([], [CryptoConfigView], ['query']),
    'getCryptoDepositInfo' : IDL.Func([IDL.Text], [Result_4], ['query']),
    'getCryptoPaymentStatus' : IDL.Func([IDL.Text], [Result_3], ['query']),
    'getDashboardData' : IDL.Func([], [IDL.Text], []),
    'getNAKPrice' : IDL.Func([], [IDL.Text], []),
    'getOrderStatus' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getPaymentStatus' : IDL.Func([IDL.Text], [PaymentStatus], []),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getTokenImage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'getTokenProfile' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'getTreasuryTokens' : IDL.Func([], [IDL.Text], []),
    'handlePaymentConfirmation' : IDL.Func([IDL.Text], [Result_2], []),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'releaseExpiredOrders' : IDL.Func([], [IDL.Nat], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'sweepCryptoToTreasury' : IDL.Func([IDL.Text], [Result_1], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateLedgerConfig' : IDL.Func(
        [Token, IDL.Principal, IDL.Nat8, IDL.Nat],
        [Result],
        [],
      ),
    'updateTreasury' : IDL.Func(
        [IDL.Principal, IDL.Opt(IDL.Vec(IDL.Nat8))],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };